image:
  registry: m.daocloud.io/docker.io
  repository: bitnami/minio
  tag: 2022.8.22-debian-11-r0
  pullPolicy: IfNotPresent
clientImage:
  registry: m.daocloud.io/docker.io
  repository: bitnami/minio-client
  tag: 2022.8.11-debian-11-r3
containerPorts:
  api: 9000
  console: 9001
persistence:
  enabled: true
  storageClass: nfs-external-nas
  size: 200Gi
volumePermissions:
  enabled: false
  image:
    registry: m.daocloud.io/docker.io
    repository: bitnami/bitnami-shell
    tag: 11-debian-11-r28
    pullPolicy: IfNotPresent
    pullSecrets: [ ]