image:
  repository: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner
  tag: v4.0.2
  pullPolicy: IfNotPresent
nfs:
  server: 10.72.252.83
  path: /kubernetes
  mountOptions:
    - vers=4
    - minorversion=0
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
    - noresvport
  volumeName: nfs-subdir-external-provisioner-nas
  reclaimPolicy: Retain
storageClass:
  create: true
  name: nfs-external-nas
  defaultClass: true
  archiveOnDelete: false