image:
  repository: docker.io/cnconti/simulation-frontend-vue
  tag: "v1.0.0"
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
  hosts:
    - host: simulation.zju.cnconti.tech
      paths:
        - path: /(.*)
          pathType: ImplementationSpecific
  tls: []
