kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: 0.0.0.0
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 32080
        hostPort: 80
        protocol: TCP
      - containerPort: 32443
        hostPort: 443
        protocol: TCP
      - containerPort: 32022
        hostPort: 1022
        protocol: TCP
      - containerPort: 30848
        hostPort: 2848
        protocol: TCP
      - containerPort: 31848
        hostPort: 3848
        protocol: TCP
  # - role: worker
  # - role: worker
  # - role: worker
