apiVersion: v1
kind: ServiceAccount
metadata:
  name: conti-test  # sa-name
  labels:
    app.kubernetes.io/service: my-sshd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: conti-test-rolebinding # sa-rolebinding
  labels:
    app.kubernetes.io/service: my-sshd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: conti-test  # sa-name