apiVersion: v1
kind: ServiceAccount
metadata:
  name: conti-test  # sa-name
  namespace: test   # sa-namespace
  labels:
    app.kubernetes.io/service: my-sshd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: conti-test-clusterrolebinding # sa-clusterrolebinding
  labels:
    app.kubernetes.io/service: my-sshd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: conti-test # sa-name
    namespace: test  # sa-namespace