image:
  repository: insecure.docker.registry.local:80/ghcr.io/helm/chartmuseum
  tag: v0.13.1
  pullPolicy: IfNotPresent
volumePermissions:
  image:
    registry: insecure.docker.registry.local:80/docker.io
    repository: bitnami/minideb
    tag: buster
    pullPolicy: IfNotPresent
persistence:
  enabled: true
  storageClass: rook-cephfs-01
  size: 10Gi
env:
  open:
    DISABLE_API: false
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: self-signed-clusterissuer
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - name: chartmuseum.local
      path: /?(.*)
      tls: true
      tlsSecret: chartmuseum.local-tls
