image:
  registry: localhost:5000/docker.io
  repository: bitnami/nginx
  tag: 1.21.4-debian-10-r0
  pullPolicy: IfNotPresent
  pullSecrets: [ ]
extraVolumes:
  - name: git-ssh-key-vol
    secret:
      secretName: git-ssh-key
      items:
        - key: id_rsa
          path: id_rsa
          mode: 0600
service:
  type: ClusterIP
cloneStaticSiteFromGit:
  image:
    registry: localhost:5000/docker.io
    repository: bitnami/git
    tag: 2.33.0-debian-10-r76
  enabled: true
  repository: git@github.com:RockConti/ContiDocs.git
  branch: main
  interval: 120
  extraVolumeMounts:
    - name: git-ssh-key-vol
      mountPath: /root/.ssh
  extraEnvVars:
    - name: GIT_SSH_COMMAND
      value: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: self-signed-cluster-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hostname: docs.local
  path: /?(.*)
  tls: false
  extraTls:
    - secretName: docs.local-tls
    - hosts:
        - docs.local
